### ISSUE TITLE
Design Docs?

### ISSUE THREAD

**Issue by dhanna11** [aswaterman/trainwreck#1]
Thank you for posting this!
Do you have any docs describing this early implementation? Particularly the Vector Unit. Imagine it's a predecessor to Hwacha? 

I'm doing research with [abstract @ CMU ECE](http://abstract.ece.cmu.edu/) and we're developing vector units. Just having code to reference helps a ton! Thanks again!

**Comment by aswaterman** [comment]
Not sure about this version of the RTL, but @yunsup’s dissertation describes a newer version of a related vector microarchitecture. https://www2.eecs.berkeley.edu/Pubs/TechRpts/2016/EECS-2016-117.html

**Comment by aswaterman** [comment]
And Krste’s dissertation is a great resource on the broader topic of vector microarchitecture: https://people.eecs.berkeley.edu/~krste/thesis.pdf
